---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi.hetzner.cloud
  labels:
    {{- include "csi-hcloud.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: true
