---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: kube-system
  name: {{ .Values.storageClass.name }}
  {{ if .Values.storageClass.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{ end }}
  labels:
    {{- include "csi-hcloud.labels" . | nindent 4 }}
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
